title: Kate Higa
description: >-
  Kate Higa's website
markdown: kramdown
social_links:
  - { platform: GitHub,         user_url: "https://github.com/khiga8" }
  - { platform: Dev.to,          user_url: "https://dev.to/kateh" }
  - { platform: Twitter,        user_url: "https://twitter.com/kate8keito" }
kramdown:
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
